// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using api.Data;

namespace api.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220921122515_IM")]
    partial class IM
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("api.Model.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Robert Kemmer"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Carrie Daugherty"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Sophia Dickinson"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Tommy Barton"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Brandon Heathcote"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Ruth Kuhn"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Marcia McClure"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Rachel Rutherford"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Roger Lynch"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Randal King"
                        });
                });

            modelBuilder.Entity("api.Model.BlogPost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<string>("Body")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("BlogPosts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 2,
                            Body = "Aut sit quam laborum autem corporis cum deleniti ducimus.\nAut et reprehenderit qui porro quo temporibus officia eligendi et.\nVoluptates doloremque tempora tempora voluptatibus.\nNesciunt ab saepe est sit explicabo.\nDolorem asperiores eius.\nEt quia asperiores dolore facere.\nDicta sunt placeat.\nMinus aliquid rerum rerum dolores minima.\nAspernatur corporis consectetur iure reprehenderit officiis.\nEt omnis adipisci dolorem suscipit ad ut.",
                            TimeStamp = new DateTime(2022, 9, 21, 13, 25, 15, 179, DateTimeKind.Local).AddTicks(3235),
                            Title = "Minus sed dolorem sed."
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 8,
                            Body = "Sunt sequi maiores qui dolores ut aut molestiae cumque hic.\nAb vel facilis est eligendi doloremque necessitatibus aut corporis.\nIllum sed pariatur quaerat facere voluptatum.\nConsequatur minus iusto eos dolorum ut eum.\nIpsam ab aliquam nesciunt et explicabo qui id esse omnis.\nEt quia doloremque officia dolorum reiciendis numquam.\nAd tenetur eos aut eum omnis.\nQuam ut sint sint et laudantium.\nDolor vel reiciendis quidem hic.\nVel dicta mollitia iusto atque incidunt.",
                            TimeStamp = new DateTime(2022, 9, 21, 13, 25, 15, 181, DateTimeKind.Local).AddTicks(230),
                            Title = "Et excepturi dicta sint."
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 9,
                            Body = "Voluptate saepe aut doloribus quia dolorem officiis qui quis tempore.\nSunt et nisi inventore quis reprehenderit est est voluptatibus.\nOmnis architecto amet.\nNihil in voluptatem sint voluptatem.\nEum cumque doloremque accusantium sunt voluptatem.\nSed vel voluptas iste veritatis impedit voluptas molestias recusandae.\nQuia voluptatum hic voluptas.\nFugiat eos et illum et quidem rem.\nQuisquam deleniti modi ut non reprehenderit totam voluptatem atque.\nAnimi ducimus quibusdam eius.",
                            TimeStamp = new DateTime(2022, 9, 21, 13, 25, 15, 181, DateTimeKind.Local).AddTicks(1177),
                            Title = "Nisi reiciendis qui vel."
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 5,
                            Body = "Quaerat aut dignissimos velit aut exercitationem et ipsum qui.\nIncidunt sequi qui quae ipsa beatae voluptas rem in.\nTotam qui eligendi.\nAliquid aut id laborum reprehenderit.\nQui veritatis temporibus nihil molestias maxime aperiam accusantium quia harum.\nUllam molestiae qui doloribus ducimus porro placeat.\nReprehenderit officiis saepe praesentium.\nCorporis odio veniam amet pariatur incidunt natus aliquam.\nDeleniti corporis dolorem commodi accusantium sed exercitationem ipsa vel.\nVoluptas mollitia ipsum saepe sapiente.",
                            TimeStamp = new DateTime(2022, 9, 21, 13, 25, 15, 181, DateTimeKind.Local).AddTicks(1794),
                            Title = "Quo consequatur vero nulla."
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 3,
                            Body = "Quae iste id veritatis ea quasi laudantium nulla dolor necessitatibus.\nEnim sint ducimus.\nQui dicta eligendi numquam debitis ut.\nPerspiciatis optio dolores.\nPerspiciatis quia et rerum.\nIn illum dolor.\nMaxime error corporis fuga laudantium fugiat.\nQuidem praesentium eligendi quia.\nDucimus provident dignissimos illum rem assumenda iste est.\nAut et non enim non eos molestiae incidunt qui dolores.",
                            TimeStamp = new DateTime(2022, 9, 21, 13, 25, 15, 181, DateTimeKind.Local).AddTicks(2372),
                            Title = "Ut neque maiores iusto."
                        },
                        new
                        {
                            Id = 6,
                            AuthorId = 5,
                            Body = "Quasi placeat quae voluptatem quam vitae consequatur consequatur deleniti.\nTemporibus voluptatum magni.\nAut quaerat magni dignissimos minus expedita quis.\nRecusandae optio enim voluptate rerum.\nOfficiis sint iusto at.\nAperiam ea sit excepturi.\nSunt non ut sed temporibus iusto.\nQui aspernatur tempora est adipisci.\nSimilique rerum id voluptate porro vel ut.\nAut dignissimos consequatur recusandae error expedita itaque nostrum aspernatur adipisci.",
                            TimeStamp = new DateTime(2022, 9, 21, 13, 25, 15, 181, DateTimeKind.Local).AddTicks(2843),
                            Title = "Id perferendis soluta quaerat."
                        },
                        new
                        {
                            Id = 7,
                            AuthorId = 8,
                            Body = "Aliquam error et ut qui nemo esse molestias soluta.\nAccusamus et culpa fuga nobis.\nDolorem et natus atque.\nAmet tempora dolor.\nNesciunt alias doloremque ut ducimus ut.\nQui pariatur sequi sequi ipsam repellat veritatis nihil.\nCorporis aliquam magnam.\nDoloremque impedit rem molestias culpa culpa perferendis ipsam voluptatem.\nEt laboriosam quisquam itaque distinctio corporis eum id.\nLaboriosam quia voluptas qui.",
                            TimeStamp = new DateTime(2022, 9, 21, 13, 25, 15, 181, DateTimeKind.Local).AddTicks(3343),
                            Title = "Maxime harum officiis aut."
                        },
                        new
                        {
                            Id = 8,
                            AuthorId = 5,
                            Body = "Blanditiis temporibus non aut doloribus vel qui provident cupiditate.\nAccusamus a vel qui consectetur.\nVel mollitia veritatis.\nIn est cumque accusantium repudiandae et.\nReiciendis alias aut est velit.\nPraesentium et officiis eos commodi qui.\nNon est eos veniam commodi eum autem.\nUt vel porro exercitationem aut nesciunt blanditiis consequatur sunt et.\nAutem fugit rem.\nUnde et blanditiis dolores sint tenetur ipsam.",
                            TimeStamp = new DateTime(2022, 9, 21, 13, 25, 15, 181, DateTimeKind.Local).AddTicks(3778),
                            Title = "Provident necessitatibus dolorem iste."
                        },
                        new
                        {
                            Id = 9,
                            AuthorId = 10,
                            Body = "Repellendus esse nam non qui voluptatem odio fuga.\nQui enim corporis consequatur inventore.\nUt corporis aliquid dignissimos quod dolore enim et et.\nOfficiis asperiores modi et ut et mollitia ut dolorem voluptatem.\nLabore provident iste autem doloremque ut nostrum ut.\nAdipisci repudiandae saepe provident.\nRatione sint veritatis ducimus vel voluptatum omnis possimus.\nRerum voluptas numquam adipisci doloribus delectus quo sit.\nEaque odit asperiores assumenda.\nEt impedit nisi sit quam omnis eligendi sapiente aspernatur.",
                            TimeStamp = new DateTime(2022, 9, 21, 13, 25, 15, 181, DateTimeKind.Local).AddTicks(4266),
                            Title = "Qui et molestias amet."
                        },
                        new
                        {
                            Id = 10,
                            AuthorId = 7,
                            Body = "Dignissimos perspiciatis repudiandae deleniti saepe est laudantium.\nImpedit corporis enim et eos minus vero molestiae porro.\nQuisquam velit id eaque blanditiis nisi.\nRerum maiores incidunt non voluptatum accusamus ab dolor vel minus.\nConsectetur sint debitis amet amet saepe.\nPorro ratione voluptas fugiat tempora et voluptatem repellat.\nAdipisci quia repellendus voluptate sunt sunt atque rerum.\nUt quis ut iusto modi magnam ab.\nCommodi ut sed et provident modi nulla voluptate id adipisci.\nFugit possimus maiores voluptatem voluptatum quia vero inventore.",
                            TimeStamp = new DateTime(2022, 9, 21, 13, 25, 15, 181, DateTimeKind.Local).AddTicks(4796),
                            Title = "Porro quia repudiandae provident."
                        },
                        new
                        {
                            Id = 11,
                            AuthorId = 1,
                            Body = "Error tenetur id in minima molestiae beatae repellendus tempora aut.\nAutem dolore distinctio.\nItaque alias aliquid vel vel fugiat eos magnam accusantium possimus.\nConsequatur consectetur voluptatem tempore sapiente.\nQuia similique ut enim labore aut blanditiis.\nDeserunt sit provident odit ut.\nDebitis adipisci nesciunt sunt voluptas ab labore eius.\nCumque nihil culpa.\nDelectus natus rerum omnis iste sint esse dolorum.\nEligendi et cumque asperiores saepe aut modi quas.",
                            TimeStamp = new DateTime(2022, 9, 21, 13, 25, 15, 181, DateTimeKind.Local).AddTicks(5416),
                            Title = "Voluptas ea dolorum doloremque."
                        },
                        new
                        {
                            Id = 12,
                            AuthorId = 4,
                            Body = "Aperiam non ut repudiandae.\nTenetur rem ut similique distinctio consequatur.\nImpedit nihil similique aut amet qui.\nVelit et provident.\nSuscipit sequi consequuntur asperiores deserunt consequatur.\nTemporibus similique provident iure at fugiat non.\nEaque nam sed.\nVeritatis eaque fuga ea ea sint.\nEa a ut aut ut libero et ut perferendis possimus.\nSapiente aut eveniet consequatur.",
                            TimeStamp = new DateTime(2022, 9, 21, 13, 25, 15, 181, DateTimeKind.Local).AddTicks(5927),
                            Title = "Qui temporibus architecto iusto."
                        },
                        new
                        {
                            Id = 13,
                            AuthorId = 9,
                            Body = "Voluptas sit dolor in repellat architecto rem aliquid.\nFacere quisquam deleniti expedita aut id illum natus.\nQuisquam aliquid nostrum adipisci magnam.\nNihil quia non illo ipsum dolorem dignissimos dicta nam.\nDeserunt est amet laborum.\nMollitia doloremque consectetur corporis.\nNon deleniti modi.\nEa ab labore nam animi et ducimus similique non asperiores.\nCum perspiciatis quam dolor aut nemo quidem vel.\nEsse eum harum hic illo quia.",
                            TimeStamp = new DateTime(2022, 9, 21, 13, 25, 15, 181, DateTimeKind.Local).AddTicks(6343),
                            Title = "Quibusdam a voluptatem at."
                        },
                        new
                        {
                            Id = 14,
                            AuthorId = 4,
                            Body = "Aspernatur rerum et sed.\nDolor corrupti dolorem facere accusantium nulla consectetur.\nError ab laborum aut quam cumque saepe libero voluptas totam.\nQuam nostrum laborum voluptatum quia ut cum.\nMinus totam in ut assumenda veritatis ullam cupiditate.\nEst nihil reprehenderit maiores.\nDoloremque quos architecto quo dicta rem.\nConsequatur iste sit quia beatae optio exercitationem.\nPerferendis doloribus ea ut.\nPraesentium ducimus maiores ratione.",
                            TimeStamp = new DateTime(2022, 9, 21, 13, 25, 15, 181, DateTimeKind.Local).AddTicks(6803),
                            Title = "Aspernatur saepe et voluptatem."
                        },
                        new
                        {
                            Id = 15,
                            AuthorId = 9,
                            Body = "Inventore beatae officia.\nQuaerat sed in laudantium quaerat quia qui commodi repudiandae dolore.\nEst commodi alias ex dolores distinctio ullam quae.\nReiciendis qui quas molestiae accusamus eos ut quis fuga.\nEnim explicabo quos porro aperiam ab laborum.\nRatione qui sit explicabo sed quod esse.\nQui quia qui laborum.\nOmnis doloremque omnis alias tempore.\nVoluptatum mollitia quia vero assumenda quod autem.\nHarum velit facilis delectus corporis occaecati dolores sequi et consequatur.",
                            TimeStamp = new DateTime(2022, 9, 21, 13, 25, 15, 181, DateTimeKind.Local).AddTicks(7281),
                            Title = "Hic quia quia maxime."
                        },
                        new
                        {
                            Id = 16,
                            AuthorId = 9,
                            Body = "Tempora omnis aut dolor excepturi et minus.\nCommodi iusto eos non voluptatem veniam dolore aliquid.\nAssumenda repellendus a itaque.\nSint explicabo tempora id.\nHic fugit fuga pariatur.\nAut similique harum eius minus velit praesentium similique totam non.\nAccusamus eum quia dolores fuga natus provident.\nAsperiores est possimus laborum architecto aperiam sint hic voluptates earum.\nAnimi id qui quia quae qui et accusantium dolorum.\nNemo numquam quos aut unde est impedit sit rem quas.",
                            TimeStamp = new DateTime(2022, 9, 21, 13, 25, 15, 181, DateTimeKind.Local).AddTicks(7822),
                            Title = "Ab voluptas molestias quo."
                        },
                        new
                        {
                            Id = 17,
                            AuthorId = 4,
                            Body = "A natus sit vel.\nOmnis et nobis voluptas.\nVeniam non neque soluta ut sed voluptates recusandae est.\nUt animi cupiditate iure quia recusandae iusto.\nReprehenderit sit consequatur qui recusandae sint.\nExplicabo voluptas aut impedit facere officia.\nNobis soluta commodi et vero temporibus provident at tempore.\nDolorem qui eos ex aperiam quibusdam est ipsam fugit.\nNostrum nemo et iste.\nDolore amet debitis eligendi odit.",
                            TimeStamp = new DateTime(2022, 9, 21, 13, 25, 15, 181, DateTimeKind.Local).AddTicks(8311),
                            Title = "Qui minus at labore."
                        },
                        new
                        {
                            Id = 18,
                            AuthorId = 3,
                            Body = "Accusantium impedit beatae est et ut ut sed error.\nIllo eos inventore quae.\nQui rerum in excepturi.\nIllum consequatur modi est animi et.\nError in ut consequatur.\nOdio adipisci est ut labore totam.\nFacere a distinctio asperiores quasi.\nAb qui facilis et.\nExercitationem occaecati rerum sed voluptatem eius atque totam quae.\nAutem dolor et voluptas qui.",
                            TimeStamp = new DateTime(2022, 9, 21, 13, 25, 15, 181, DateTimeKind.Local).AddTicks(8793),
                            Title = "Recusandae et praesentium repudiandae."
                        },
                        new
                        {
                            Id = 19,
                            AuthorId = 7,
                            Body = "Ipsum sed omnis quam.\nIllum voluptatem quam omnis.\nOccaecati distinctio placeat itaque quis qui et ipsum omnis.\nAssumenda nihil doloremque autem dolor doloremque.\nCum sed aliquid a consequatur est libero quia.\nAmet fugit et ea sit quae.\nNihil vero quia debitis reprehenderit odit.\nAutem eligendi quisquam aut.\nPlaceat dicta iure et consequuntur sequi.\nRerum sed officiis voluptatem ab vitae.",
                            TimeStamp = new DateTime(2022, 9, 21, 13, 25, 15, 181, DateTimeKind.Local).AddTicks(9212),
                            Title = "Optio eos ad ullam."
                        },
                        new
                        {
                            Id = 20,
                            AuthorId = 9,
                            Body = "Dicta est non est.\nIllo sequi enim similique sit natus ut.\nQui veniam autem voluptatem et officiis id dolore.\nNeque nostrum omnis impedit architecto quibusdam in modi itaque.\nIure similique quibusdam.\nIllum deleniti accusamus amet aut aut et omnis.\nId quas quia et odio error totam sint.\nUt tempora natus quidem inventore consequatur voluptatibus.\nOptio nisi qui natus aut.\nNon et iste.",
                            TimeStamp = new DateTime(2022, 9, 21, 13, 25, 15, 181, DateTimeKind.Local).AddTicks(9631),
                            Title = "Aut ut temporibus nemo."
                        },
                        new
                        {
                            Id = 21,
                            AuthorId = 9,
                            Body = "Est et rerum quia placeat asperiores dolores distinctio rem vitae.\nNam similique aut dolor nihil veritatis quia laborum sit.\nNesciunt beatae quisquam nihil reprehenderit sit aut.\nSed ut aut sed minima tenetur maiores aut.\nIncidunt commodi error nobis molestiae deleniti et.\nCommodi excepturi autem esse accusamus deleniti.\nAmet reprehenderit qui sunt.\nDolor ea consequatur magnam.\nItaque nulla perferendis magni nostrum voluptatem adipisci enim blanditiis aut.\nEt debitis ut animi.",
                            TimeStamp = new DateTime(2022, 9, 21, 13, 25, 15, 182, DateTimeKind.Local).AddTicks(103),
                            Title = "Non nobis voluptas consequatur."
                        },
                        new
                        {
                            Id = 22,
                            AuthorId = 7,
                            Body = "Nam possimus expedita ut necessitatibus.\nVelit rerum qui officiis omnis enim facere.\nQuidem illo minima architecto commodi sit aut velit quas ut.\nSint numquam aut similique assumenda sit qui.\nDolorum enim dicta ex repellendus ea est dolor.\nQuidem aut optio corporis quia dolore.\nId minus tenetur nemo quia quia magnam magnam possimus omnis.\nQuis odio ipsam ab ut.\nSimilique magni porro unde optio dolores.\nPorro in cum omnis ea sed ut reprehenderit.",
                            TimeStamp = new DateTime(2022, 9, 21, 13, 25, 15, 182, DateTimeKind.Local).AddTicks(588),
                            Title = "Perferendis accusantium libero molestias."
                        },
                        new
                        {
                            Id = 23,
                            AuthorId = 10,
                            Body = "Quam esse voluptatem fugiat animi aut accusantium commodi nisi.\nQui natus veniam.\nAsperiores non esse et labore minima deserunt molestiae.\nRem nulla omnis excepturi voluptatibus ipsam et.\nPerferendis nesciunt in ratione porro.\nQuo explicabo corrupti facilis ex inventore natus consectetur.\nSint non in odio deserunt veritatis quibusdam aut et.\nAut unde doloribus ab dolores quae.\nVoluptates assumenda similique.\nNihil deserunt minima quo cumque vel.",
                            TimeStamp = new DateTime(2022, 9, 21, 13, 25, 15, 182, DateTimeKind.Local).AddTicks(1109),
                            Title = "Aut delectus eaque vel."
                        },
                        new
                        {
                            Id = 24,
                            AuthorId = 8,
                            Body = "Alias harum voluptatibus qui officiis.\nQuis eius inventore sit et fugiat qui est quae.\nAnimi nemo ratione autem dolorum odio non itaque quia id.\nMagnam quae totam consequatur et repudiandae ut maiores esse sint.\nQuia architecto atque aliquid ut autem.\nDignissimos eligendi reiciendis voluptas omnis aperiam non quisquam dolor distinctio.\nQuam ipsa laudantium enim rerum eaque ipsum.\nQuia voluptatem et debitis id et rem.\nDolores architecto enim enim.\nQuo repellat cum.",
                            TimeStamp = new DateTime(2022, 9, 21, 13, 25, 15, 182, DateTimeKind.Local).AddTicks(1616),
                            Title = "Harum ut et ut."
                        },
                        new
                        {
                            Id = 25,
                            AuthorId = 10,
                            Body = "Voluptates minus est.\nAsperiores rem repellat ut consequuntur dignissimos.\nPossimus ab sint cupiditate.\nLabore dolores nostrum saepe autem facilis accusamus iure totam.\nQuae repellendus ea aperiam omnis rerum sequi.\nFugit amet ut ipsam.\nAlias qui incidunt rerum et sunt suscipit temporibus.\nVoluptatem sunt tempore.\nAsperiores ut veniam voluptatem et.\nA velit molestiae non.",
                            TimeStamp = new DateTime(2022, 9, 21, 13, 25, 15, 182, DateTimeKind.Local).AddTicks(2086),
                            Title = "Repudiandae atque veniam iusto."
                        },
                        new
                        {
                            Id = 26,
                            AuthorId = 6,
                            Body = "Aut suscipit omnis molestiae et quis placeat error optio.\nUllam magni autem.\nQuidem ut ea sed necessitatibus et sapiente pariatur quia ab.\nModi sunt recusandae est at.\nAutem minus doloribus minima vel ut placeat pariatur nihil temporibus.\nSimilique eos sint dolorem dolorum laudantium in ad.\nEst voluptate doloribus voluptas tenetur perferendis quas similique.\nQuo illum officiis voluptas aperiam.\nQui et nobis qui qui est ex.\nDolorem labore minima laudantium.",
                            TimeStamp = new DateTime(2022, 9, 21, 13, 25, 15, 182, DateTimeKind.Local).AddTicks(2476),
                            Title = "Explicabo saepe exercitationem id."
                        },
                        new
                        {
                            Id = 27,
                            AuthorId = 2,
                            Body = "Sed minima eum maxime voluptatem quia.\nEaque sit similique doloribus ut nulla est dolorem velit.\nIllum omnis facere unde consequuntur suscipit.\nNeque animi cum unde.\nEaque cum id praesentium laudantium.\nFacere quia et et commodi sit eligendi molestiae.\nConsectetur at qui iste quidem quisquam aut dolor suscipit.\nEt asperiores rerum neque culpa unde est.\nNam qui necessitatibus iure excepturi.\nRepellat architecto quis omnis dolorem velit.",
                            TimeStamp = new DateTime(2022, 9, 21, 13, 25, 15, 182, DateTimeKind.Local).AddTicks(2983),
                            Title = "Provident animi aut ea."
                        },
                        new
                        {
                            Id = 28,
                            AuthorId = 8,
                            Body = "Quia sed repudiandae et itaque.\nEnim at mollitia minus aut sapiente quasi aut porro voluptas.\nVeniam eveniet aut.\nAut iste natus et quia.\nEt officiis aut exercitationem in magni ad.\nNon laboriosam aut quia asperiores.\nExpedita temporibus ut.\nVoluptas nihil veritatis optio delectus.\nEsse et tempora delectus adipisci natus aliquid modi laborum.\nUt voluptatibus qui iusto voluptate.",
                            TimeStamp = new DateTime(2022, 9, 21, 13, 25, 15, 182, DateTimeKind.Local).AddTicks(3504),
                            Title = "Vero optio unde doloremque."
                        },
                        new
                        {
                            Id = 29,
                            AuthorId = 9,
                            Body = "Architecto ut nobis.\nEius quis nostrum aut et iste tempora et.\nAut maxime et nemo.\nUt doloribus temporibus mollitia.\nEst tempore sed fugiat eos et voluptates corporis.\nUt vel laboriosam placeat ut minima aut.\nInventore sed asperiores est quia.\nEa omnis distinctio.\nCorrupti est eius iusto tempora deleniti consectetur repudiandae perferendis sit.\nMolestiae id impedit magnam porro consequatur.",
                            TimeStamp = new DateTime(2022, 9, 21, 13, 25, 15, 182, DateTimeKind.Local).AddTicks(3917),
                            Title = "Quibusdam possimus amet molestiae."
                        },
                        new
                        {
                            Id = 30,
                            AuthorId = 4,
                            Body = "Optio non tempore animi.\nEst mollitia et minima velit in quam eligendi quis aut.\nEos natus fuga voluptatem a illum harum.\nQuis voluptatum ea impedit eaque aut libero.\nPraesentium iusto cupiditate quas iste debitis quia.\nEsse eius quia tempora accusantium.\nIste et voluptatem omnis soluta.\nMaxime voluptas eius debitis ullam nesciunt.\nMolestias dolore necessitatibus voluptas enim.\nAccusantium sapiente quaerat voluptas animi aperiam maiores.",
                            TimeStamp = new DateTime(2022, 9, 21, 13, 25, 15, 182, DateTimeKind.Local).AddTicks(4332),
                            Title = "Perspiciatis asperiores consequatur doloremque."
                        });
                });

            modelBuilder.Entity("api.Model.BlogPost", b =>
                {
                    b.HasOne("api.Model.Author", "Author")
                        .WithMany("BlogPosts")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("api.Model.Author", b =>
                {
                    b.Navigation("BlogPosts");
                });
#pragma warning restore 612, 618
        }
    }
}
