// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using api.Data;

namespace api.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20221013235407_Author model update")]
    partial class Authormodelupdate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("api.Model.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Penny Koelpin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Irvin Nader"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Salvador Pfannerstill"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Jeffery Corkery"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Shirley Jenkins"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Dorothy Anderson"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Virgil Legros"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Leona Bruen"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Jessie Schoen"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Nellie Zemlak"
                        });
                });

            modelBuilder.Entity("api.Model.BlogPost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<string>("Body")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("BlogPosts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 9,
                            Body = "Qui incidunt atque.\nQui modi animi nostrum quia consequatur.\nDolor similique et quo quia dolores eos sed maiores velit.\nEt cumque sed accusamus.\nRerum tempore vel laudantium rem.\nOfficia qui facilis voluptatem et est sint ut id aliquid.\nQui quod optio ea.\nOptio natus quia.\nMinus est sunt animi dolor laboriosam quo.\nPorro et quibusdam perspiciatis occaecati quo reiciendis eius et.",
                            TimeStamp = new DateTime(2022, 10, 14, 0, 54, 7, 110, DateTimeKind.Local).AddTicks(4575),
                            Title = "Eligendi voluptatibus quod porro."
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 9,
                            Body = "Eveniet molestiae aut vel quia hic debitis reiciendis illum.\nRecusandae non voluptatibus aut quae.\nQui reiciendis ab dolorem maiores omnis expedita.\nUt quisquam sit earum quo.\nTenetur magnam quis et cum.\nUt a ut sint.\nRerum reiciendis sed qui fuga repellat quia voluptatem voluptatem.\nAdipisci ut dolorum qui nisi est culpa voluptatum.\nVoluptas itaque eos rem iure nobis.\nDolor sit accusamus quidem fuga iusto magni maiores ut sunt.",
                            TimeStamp = new DateTime(2022, 10, 14, 0, 54, 7, 113, DateTimeKind.Local).AddTicks(2137),
                            Title = "Non ipsum veniam dignissimos."
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 5,
                            Body = "Occaecati quisquam possimus sit libero reiciendis suscipit ea voluptatem atque.\nVoluptatem ut et.\nVel ut nihil illum debitis voluptatem nobis.\nPossimus aut harum.\nAssumenda voluptatem accusamus velit minus temporibus.\nDolorum facere et.\nAliquam sed repellat totam ipsam qui aliquid reiciendis.\nPariatur et rerum.\nSunt ut aut assumenda fugiat porro repellat repudiandae eaque.\nError vitae qui veniam ex commodi rerum.",
                            TimeStamp = new DateTime(2022, 10, 14, 0, 54, 7, 113, DateTimeKind.Local).AddTicks(3084),
                            Title = "Quo ad quisquam reiciendis."
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 9,
                            Body = "Debitis soluta consequatur eos voluptate consequuntur unde.\nCumque soluta inventore et eum est dolore repellendus.\nEt facere numquam.\nIusto eum et vero repellat et velit ut.\nBlanditiis in quia quis modi.\nTotam at deserunt.\nQuos debitis eos ea reprehenderit expedita cupiditate tempore quidem.\nPorro iste deleniti.\nSint dignissimos ullam et.\nVelit molestias ut.",
                            TimeStamp = new DateTime(2022, 10, 14, 0, 54, 7, 113, DateTimeKind.Local).AddTicks(3505),
                            Title = "Facere amet ut ducimus."
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 7,
                            Body = "Laudantium nesciunt voluptatem sit eaque delectus est.\nSunt voluptatibus rem sed rem earum natus debitis mollitia.\nExplicabo necessitatibus consequatur dolor temporibus delectus pariatur dolor minima qui.\nRem dolor repudiandae voluptatem.\nNon deleniti est sed sint excepturi molestias aut accusamus ipsam.\nAut earum similique.\nDolor autem voluptas eum laborum dolor nobis consequatur aliquid.\nEos est culpa mollitia aspernatur.\nNatus ab quos minus vitae aut inventore eum qui.\nUt voluptates rem earum quae labore.",
                            TimeStamp = new DateTime(2022, 10, 14, 0, 54, 7, 113, DateTimeKind.Local).AddTicks(3863),
                            Title = "Iure tempora deleniti quas."
                        },
                        new
                        {
                            Id = 6,
                            AuthorId = 8,
                            Body = "Ut et non aut nihil sed expedita.\nMolestiae quas assumenda sint totam possimus ducimus quo cumque.\nMinus rerum et incidunt repudiandae est saepe voluptate.\nDolorum voluptatibus modi sequi quam.\nDoloremque molestias est sed ut soluta vero est omnis praesentium.\nQui a voluptatum quis temporibus officiis expedita voluptas rerum.\nQui nemo necessitatibus facere eius perferendis sint aperiam voluptas cumque.\nAliquid similique iusto dolore possimus.\nMinus repellat debitis eius ipsa est voluptatem harum.\nRecusandae repellat eum odit error iure voluptatum eaque corporis sed.",
                            TimeStamp = new DateTime(2022, 10, 14, 0, 54, 7, 113, DateTimeKind.Local).AddTicks(4311),
                            Title = "Ea dignissimos soluta at."
                        },
                        new
                        {
                            Id = 7,
                            AuthorId = 8,
                            Body = "Sint possimus velit autem reprehenderit eaque ipsa aperiam.\nMolestiae assumenda et eligendi.\nSed quod quia minima beatae sint quia id.\nSapiente officiis non magni.\nA sit reiciendis.\nItaque non quia perferendis id.\nUnde saepe tenetur quibusdam et rerum et velit ut.\nNam inventore voluptas voluptatum qui voluptatem atque.\nDolorum qui sint eos.\nRepellat architecto inventore rerum odio consequuntur neque error occaecati alias.",
                            TimeStamp = new DateTime(2022, 10, 14, 0, 54, 7, 113, DateTimeKind.Local).AddTicks(4777),
                            Title = "Qui facere nam earum."
                        },
                        new
                        {
                            Id = 8,
                            AuthorId = 3,
                            Body = "Et nisi laudantium dolor excepturi autem eveniet at quas.\nSint ipsa earum qui quis et nobis maiores.\nQuisquam consequatur eligendi dolor veniam amet illo ratione inventore quae.\nIn veritatis beatae enim sed odit qui soluta.\nDolorum quia sed dignissimos eligendi non.\nDolorum quia quo.\nQuae velit consequatur est inventore.\nNeque sit asperiores praesentium incidunt voluptas consequatur omnis ut.\nDelectus et minima sit totam consequatur officia suscipit perspiciatis.\nMagnam corrupti quasi et iusto voluptatem nisi.",
                            TimeStamp = new DateTime(2022, 10, 14, 0, 54, 7, 113, DateTimeKind.Local).AddTicks(5156),
                            Title = "Minus sit sapiente voluptate."
                        },
                        new
                        {
                            Id = 9,
                            AuthorId = 7,
                            Body = "Enim earum enim est itaque.\nSuscipit qui soluta nisi ex sequi.\nNulla provident necessitatibus ipsa est tempore qui blanditiis iste tempore.\nNon voluptatem quia.\nQuia et ratione et in autem.\nLabore adipisci ipsam est earum non quia similique ratione porro.\nDignissimos dolor vel quibusdam expedita deserunt eum dolore quibusdam facere.\nNeque omnis repudiandae sit quo.\nEt velit iste in laborum.\nNostrum eligendi est sapiente qui recusandae dolore doloribus non reprehenderit.",
                            TimeStamp = new DateTime(2022, 10, 14, 0, 54, 7, 113, DateTimeKind.Local).AddTicks(5574),
                            Title = "Optio sed illo iure."
                        },
                        new
                        {
                            Id = 10,
                            AuthorId = 1,
                            Body = "Iste quam sit in non ut.\nIste minus omnis.\nRecusandae tenetur rerum neque suscipit.\nExercitationem occaecati aut recusandae harum et ipsam omnis voluptas.\nEst maxime laboriosam sequi voluptatem rerum quia facilis.\nEt aperiam libero quia.\nDolorem tempora ut iste ipsam aperiam qui incidunt.\nMaxime minus neque tempora voluptatum molestiae voluptas sit.\nDignissimos incidunt voluptatem.\nQui est modi maiores placeat corporis accusantium sunt quibusdam.",
                            TimeStamp = new DateTime(2022, 10, 14, 0, 54, 7, 113, DateTimeKind.Local).AddTicks(6018),
                            Title = "In doloremque nobis voluptas."
                        },
                        new
                        {
                            Id = 11,
                            AuthorId = 7,
                            Body = "Possimus labore qui sequi ut et deserunt quam.\nQuisquam qui quisquam quis tempora aut tempora sunt in aliquid.\nCommodi suscipit voluptas quis minima sed qui rerum odit.\nRepellendus impedit occaecati vitae quaerat temporibus porro architecto quisquam maxime.\nAmet incidunt voluptatem sit qui expedita et temporibus in.\nEaque velit in.\nNihil voluptates dignissimos officiis laboriosam.\nFacilis enim accusantium recusandae voluptatem sed.\nUt eius excepturi sit soluta.\nAccusantium quia aut et enim optio unde.",
                            TimeStamp = new DateTime(2022, 10, 14, 0, 54, 7, 113, DateTimeKind.Local).AddTicks(6418),
                            Title = "Velit odio voluptas ea."
                        },
                        new
                        {
                            Id = 12,
                            AuthorId = 8,
                            Body = "Earum voluptas quo aut enim.\nEum ut nesciunt debitis.\nSit asperiores eum consequatur.\nSunt necessitatibus sunt ea aut omnis qui voluptatem voluptas quia.\nTemporibus possimus corrupti id.\nAmet est quaerat cupiditate.\nSuscipit labore illum ullam.\nAccusamus ullam ut id ad.\nDolor eum officia illum voluptas.\nCorrupti iure fuga occaecati eaque aspernatur.",
                            TimeStamp = new DateTime(2022, 10, 14, 0, 54, 7, 113, DateTimeKind.Local).AddTicks(6831),
                            Title = "Nesciunt nihil at placeat."
                        },
                        new
                        {
                            Id = 13,
                            AuthorId = 1,
                            Body = "Qui enim quia.\nOmnis ut et enim veritatis laudantium nobis voluptas quam.\nEveniet eos est.\nUt temporibus voluptate quibusdam labore accusamus ut et ullam eos.\nNihil fugiat velit doloremque accusamus deserunt consequatur consectetur suscipit.\nAliquid neque quos.\nVoluptatem nihil dolor aut non.\nNeque maiores in voluptas.\nFuga nisi aperiam magnam rerum ratione.\nSint deleniti ea harum corrupti vel unde sint saepe libero.",
                            TimeStamp = new DateTime(2022, 10, 14, 0, 54, 7, 113, DateTimeKind.Local).AddTicks(7150),
                            Title = "Deserunt molestias libero enim."
                        },
                        new
                        {
                            Id = 14,
                            AuthorId = 3,
                            Body = "Numquam dolorem sed sint consequatur itaque.\nPorro quaerat et unde dolore dolore ut earum.\nEt quam est perferendis ut reprehenderit.\nUt omnis esse nemo.\nQuo quo eius vero impedit officiis.\nDicta eum harum similique in nulla rerum autem illo.\nCorporis ut et qui rerum.\nMagni reiciendis ut quas qui hic voluptatem sapiente hic harum.\nConsequatur perspiciatis numquam est.\nQuis sequi vero natus nostrum pariatur architecto.",
                            TimeStamp = new DateTime(2022, 10, 14, 0, 54, 7, 113, DateTimeKind.Local).AddTicks(7630),
                            Title = "Eos unde fuga repudiandae."
                        },
                        new
                        {
                            Id = 15,
                            AuthorId = 2,
                            Body = "Voluptatem eum voluptas eum est.\nAut aut quis.\nDolores cum libero et rerum impedit harum eum quo in.\nSaepe assumenda officiis quia et minima et id quia.\nRepellendus dignissimos impedit et magnam quis dolor est consequuntur.\nMinus alias nesciunt quisquam aut dolorum ut consequuntur praesentium.\nAmet voluptas consequuntur corrupti aliquam laborum saepe quas.\nConsequatur reiciendis quasi.\nConsectetur aliquid ut sapiente.\nEligendi suscipit blanditiis inventore quo voluptas accusantium saepe laborum.",
                            TimeStamp = new DateTime(2022, 10, 14, 0, 54, 7, 113, DateTimeKind.Local).AddTicks(8009),
                            Title = "Voluptas sit neque nihil."
                        },
                        new
                        {
                            Id = 16,
                            AuthorId = 2,
                            Body = "Deleniti dolorum praesentium voluptatem eius.\nQuidem deleniti tempore expedita voluptatem fugiat nam.\nUt consequatur est distinctio esse iusto quia labore magni.\nEa laudantium ea alias quod et dicta.\nVelit autem quisquam similique necessitatibus repudiandae quod enim inventore.\nDolor ea reprehenderit recusandae commodi explicabo rerum dolor temporibus.\nEt nisi voluptatem labore corrupti nulla.\nPossimus amet harum id est sunt iste harum officiis vitae.\nVoluptatum id sint ratione autem enim.\nQui eius molestiae aspernatur ut ea.",
                            TimeStamp = new DateTime(2022, 10, 14, 0, 54, 7, 113, DateTimeKind.Local).AddTicks(8407),
                            Title = "Odio aperiam quae omnis."
                        },
                        new
                        {
                            Id = 17,
                            AuthorId = 10,
                            Body = "Atque vitae quae a voluptatibus dicta nihil sed.\nFugiat quo ullam quos.\nEt nemo illo.\nAtque delectus aut omnis omnis fuga.\nExpedita sint ad dolor sit eos nihil.\nIncidunt animi voluptatem et omnis itaque inventore hic voluptatem.\nEveniet eum consequuntur est aliquam.\nEt modi aliquam.\nSaepe possimus nihil voluptatem quam molestiae quia dolorem.\nLaboriosam voluptas ut esse.",
                            TimeStamp = new DateTime(2022, 10, 14, 0, 54, 7, 113, DateTimeKind.Local).AddTicks(8822),
                            Title = "Ad impedit dolores vero."
                        },
                        new
                        {
                            Id = 18,
                            AuthorId = 6,
                            Body = "Sint nihil perferendis qui quos.\nEt ea ab distinctio sequi consequuntur aut est est.\nVoluptatum saepe repellat aut aliquid et necessitatibus et vel ducimus.\nUt animi aliquid voluptas consectetur dolor rerum id tempora debitis.\nNon blanditiis dolor.\nAd molestias asperiores.\nQui commodi rerum rerum.\nOccaecati non eos molestiae ut provident non sint ipsa.\nEnim et optio qui delectus ut dolorem officiis unde consequatur.\nNobis ut fugiat sit nisi eum.",
                            TimeStamp = new DateTime(2022, 10, 14, 0, 54, 7, 113, DateTimeKind.Local).AddTicks(9163),
                            Title = "Quaerat esse molestiae officiis."
                        },
                        new
                        {
                            Id = 19,
                            AuthorId = 9,
                            Body = "Similique quia voluptatem sint voluptatem fugiat optio nam aut dolorem.\nEt eius in nobis doloremque et error.\nExplicabo quidem suscipit quo reprehenderit doloremque.\nNatus ratione ea ipsam voluptas quis earum.\nMagni dolores cumque molestiae qui eaque pariatur laboriosam suscipit.\nSit molestiae fugit voluptas cumque omnis id.\nArchitecto ut quia incidunt.\nOfficiis necessitatibus molestiae ad unde quaerat.\nVoluptas ratione sapiente autem ducimus amet voluptas odio quam.\nEt exercitationem repellat quia quis aut.",
                            TimeStamp = new DateTime(2022, 10, 14, 0, 54, 7, 113, DateTimeKind.Local).AddTicks(9557),
                            Title = "Id porro error voluptas."
                        },
                        new
                        {
                            Id = 20,
                            AuthorId = 5,
                            Body = "Ullam impedit occaecati eveniet.\nEum ut porro.\nCorporis vitae ut tempore officiis sapiente id voluptatem excepturi.\nUllam id dolorum doloribus accusantium incidunt.\nQuas repellendus rerum atque.\nHarum eius tempore.\nAliquam at unde dolor et eveniet cumque eligendi earum.\nPraesentium est dolores eos.\nVoluptatum itaque quia minima iusto soluta porro quos.\nNulla quia facere assumenda minima sed ducimus voluptatem.",
                            TimeStamp = new DateTime(2022, 10, 14, 0, 54, 7, 113, DateTimeKind.Local).AddTicks(9953),
                            Title = "Autem ducimus fuga in."
                        },
                        new
                        {
                            Id = 21,
                            AuthorId = 10,
                            Body = "Hic in aperiam non ab.\nEst sint consequatur est sed consequatur neque praesentium earum.\nDolorem ut ea aut.\nQuia ratione recusandae velit id.\nEos est rem et vero impedit id tempora debitis.\nPlaceat nam soluta saepe voluptas voluptatem.\nError enim eaque.\nAutem voluptas vero dolorem cupiditate rerum repellat est magnam aspernatur.\nEnim ipsa harum et provident numquam ut.\nIste incidunt et fugiat esse.",
                            TimeStamp = new DateTime(2022, 10, 14, 0, 54, 7, 114, DateTimeKind.Local).AddTicks(305),
                            Title = "Accusantium impedit rerum assumenda."
                        },
                        new
                        {
                            Id = 22,
                            AuthorId = 9,
                            Body = "Consequatur eos cumque.\nOmnis rerum et voluptatem suscipit qui est qui fuga.\nUt aliquid quidem quaerat praesentium.\nNecessitatibus eius aut deleniti possimus enim non odio exercitationem.\nEveniet asperiores sint non minus autem laborum voluptatem officiis.\nSint hic perferendis deleniti hic dolor odio provident sit cupiditate.\nQui perspiciatis et.\nVoluptatem dolorem eius voluptatem.\nA quia ut corrupti molestiae laborum.\nEsse sunt vero id autem iure deleniti.",
                            TimeStamp = new DateTime(2022, 10, 14, 0, 54, 7, 114, DateTimeKind.Local).AddTicks(668),
                            Title = "Soluta doloribus consequatur at."
                        },
                        new
                        {
                            Id = 23,
                            AuthorId = 9,
                            Body = "Officiis in aliquam assumenda aut dolorem ducimus at inventore culpa.\nReprehenderit labore quam voluptatem.\nVoluptatibus cupiditate omnis suscipit dolore voluptatem sapiente voluptas.\nNam laboriosam veritatis velit non rerum tempore est quae.\nIste sint velit nobis possimus neque soluta.\nDoloribus est ut dolores delectus.\nConsequuntur a soluta earum consectetur qui.\nOdio non maiores eos dolorem iure et nulla quidem.\nNihil consectetur voluptas laudantium dolorem dolor voluptas.\nQuia similique nam ut soluta odio provident autem id.",
                            TimeStamp = new DateTime(2022, 10, 14, 0, 54, 7, 114, DateTimeKind.Local).AddTicks(1045),
                            Title = "Earum quia dolores non."
                        },
                        new
                        {
                            Id = 24,
                            AuthorId = 1,
                            Body = "Minus sed doloribus non unde.\nOmnis accusantium excepturi aliquid aut rerum earum consequuntur asperiores corporis.\nVoluptas ratione sit nesciunt.\nTotam dolore unde id.\nRepellendus qui deserunt autem aut quia.\nAut ut quo similique exercitationem eos qui perspiciatis voluptatem.\nSimilique quibusdam officia dolore laborum assumenda architecto.\nQui deleniti neque unde et quod.\nEarum deleniti asperiores dignissimos sint reiciendis corporis iusto.\nPerferendis facilis totam.",
                            TimeStamp = new DateTime(2022, 10, 14, 0, 54, 7, 114, DateTimeKind.Local).AddTicks(1450),
                            Title = "Magnam voluptatem minus dolores."
                        },
                        new
                        {
                            Id = 25,
                            AuthorId = 7,
                            Body = "Pariatur soluta facere.\nSed quia vel.\nTenetur eius qui impedit error eligendi explicabo.\nAliquid vel ea aut incidunt facilis ut ea sint ut.\nCorporis laudantium officiis ullam at unde sint aut veritatis voluptates.\nMinima illum et in accusantium vitae impedit commodi qui tenetur.\nNihil adipisci ut eius excepturi.\nQuia velit reprehenderit et ut non excepturi illo beatae.\nOfficiis neque quae necessitatibus aperiam asperiores molestiae aut qui rem.\nEt sit et sequi dolor perferendis recusandae omnis soluta.",
                            TimeStamp = new DateTime(2022, 10, 14, 0, 54, 7, 114, DateTimeKind.Local).AddTicks(1817),
                            Title = "Unde veniam fuga et."
                        },
                        new
                        {
                            Id = 26,
                            AuthorId = 4,
                            Body = "Occaecati nihil nemo est sed nisi rerum neque.\nSed voluptate veritatis suscipit impedit voluptas et harum ipsa.\nOfficia incidunt id nisi consectetur adipisci culpa exercitationem in occaecati.\nConsequuntur voluptas nostrum eum.\nConsequatur quibusdam aut ex corrupti tempore.\nQui tenetur autem.\nMollitia illo repudiandae mollitia alias asperiores placeat aut esse dolor.\nSed velit ut.\nUnde rerum mollitia.\nBeatae assumenda tenetur.",
                            TimeStamp = new DateTime(2022, 10, 14, 0, 54, 7, 114, DateTimeKind.Local).AddTicks(2241),
                            Title = "Quidem aperiam porro animi."
                        },
                        new
                        {
                            Id = 27,
                            AuthorId = 3,
                            Body = "Repudiandae numquam sint reprehenderit vel dolore.\nEt atque molestiae ut dolores culpa minima delectus eligendi molestiae.\nNatus illum iusto quia autem modi debitis ullam.\nFacilis illum sequi mollitia.\nNemo enim aspernatur sed et.\nCorporis dolorem iste consequatur veritatis porro commodi earum.\nCorrupti maiores ut fugiat quia aspernatur.\nIpsa temporibus quo optio sint sint et laboriosam nihil.\nVoluptas necessitatibus dolorem nemo sit.\nEum labore autem qui quaerat et inventore expedita vero.",
                            TimeStamp = new DateTime(2022, 10, 14, 0, 54, 7, 114, DateTimeKind.Local).AddTicks(2589),
                            Title = "Omnis alias expedita nobis."
                        },
                        new
                        {
                            Id = 28,
                            AuthorId = 10,
                            Body = "Enim dolore iusto tempora nemo.\nIpsum quia temporibus aut numquam.\nId reprehenderit voluptatum fugit consectetur nemo.\nQuo mollitia hic cumque.\nEsse qui sit quo culpa porro quis.\nQui consequatur inventore rerum reprehenderit beatae debitis in.\nVeritatis qui nostrum ipsa et quia ut eum.\nEst eum odio error est voluptatem perspiciatis dolorem vel.\nSit sit mollitia quasi qui sed et.\nSit fugiat quisquam aut molestiae qui illo provident.",
                            TimeStamp = new DateTime(2022, 10, 14, 0, 54, 7, 114, DateTimeKind.Local).AddTicks(2981),
                            Title = "Et eligendi distinctio minima."
                        },
                        new
                        {
                            Id = 29,
                            AuthorId = 4,
                            Body = "Blanditiis possimus odit doloribus et culpa veniam id explicabo similique.\nCorporis eius voluptas totam excepturi.\nMolestias alias mollitia recusandae unde aspernatur et.\nEt molestias consectetur tenetur dolores aliquam rerum ipsum ut officiis.\nDelectus quod exercitationem distinctio dignissimos deserunt quod sequi nulla.\nId est et at.\nVeritatis ipsum consequatur voluptatibus voluptates expedita est doloremque fuga.\nExplicabo repellendus sapiente.\nFuga dolores tenetur blanditiis et.\nQui non laboriosam voluptatem laboriosam aut earum.",
                            TimeStamp = new DateTime(2022, 10, 14, 0, 54, 7, 114, DateTimeKind.Local).AddTicks(3360),
                            Title = "Velit similique ipsum voluptate."
                        },
                        new
                        {
                            Id = 30,
                            AuthorId = 7,
                            Body = "Veniam adipisci rem.\nVeniam delectus dolor ea impedit.\nDeserunt aliquid consequatur omnis voluptas modi doloribus est.\nIusto corporis doloremque pariatur fugiat.\nRerum aut porro tenetur velit est quis ut.\nCum sed voluptatem omnis libero corrupti qui consectetur.\nUt maxime et.\nDoloremque aut iusto quo commodi excepturi est.\nAliquam nisi quidem cumque rerum eos laudantium ea molestias.\nNemo vel magni.",
                            TimeStamp = new DateTime(2022, 10, 14, 0, 54, 7, 114, DateTimeKind.Local).AddTicks(3758),
                            Title = "Eum perferendis repellendus quia."
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("api.Model.BlogPost", b =>
                {
                    b.HasOne("api.Model.Author", "Author")
                        .WithMany("BlogPosts")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("api.Model.Author", b =>
                {
                    b.Navigation("BlogPosts");
                });
#pragma warning restore 612, 618
        }
    }
}
